[package]
name = "colors"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"
authors = ["Luke Hannan"]

[workspace]
members = [
    "crates/black",
    "crates/hextorgb",
    "crates/rgbtohex",
    "crates/colorctl",
]
default-members = ["crates/colorctl"]

[workspace.dependencies]
black = { path = "crates/black" }
clap = { version = "4.5.43", features = ["derive"] }
colored = "3.0.0"
hextorgb = { path = "crates/hextorgb", features = ["cli"] }
image = { version = "0.25.9", default-features = false, features = ["gif", "jpeg", "png", "tiff", "webp"] }
rayon = "1.10.0"
rgbtohex = { path = "crates/rgbtohex", features = ["cli"] }

[workspace.package]
edition = "2024"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = 3
