[package]
name = "hextorgb"
version = "0.6.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/luhann/colors"
authors = ["Luke Hannan"]
description = "Convert hex color codes to RGB values"

[lib]
name = "hextorgb"
path = "src/lib.rs"

[dependencies]
clap = { workspace = true, optional = true }
colored = { workspace = true, optional = true }

[features]
default = []
cli = ["dep:clap", "dep:colored"]
