[package]
name = "rgbtohex"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/luhann/colors"
authors = ["Luke Hannan"]
description = "Convert RGB color values to hex"

[lib]
name = "rgbtohex"
path = "src/lib.rs"

[dependencies]
clap = { workspace = true, optional = true }
colored = { workspace = true, optional = true }

[features]
default = []
cli = ["dep:clap", "dep:colored"]
