name: Rust Workspace CI

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-release-
            ${{ runner.os }}-cargo-

      - name: Toolchain info
        run: |
          rustc --version
          cargo --version

      - name: Check (release)
        run: cargo check --workspace --release

      - name: Build (release)
        run: cargo build --workspace --release

      - name: Tests (release)
        run: cargo test --workspace --release

      - name: Doc tests (release)
        run: cargo test --doc --workspace --release
